---
name: Lint OpenAPI Descriptions

on:
  - push

jobs:
  lint:
    name: Lint OpenAPI ${{matrix.version}} releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: '3.0'
            files: 'descriptions/**/*.yaml'
          - version: '3.1'
            files: 'descriptions-next/**/*.yaml'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.12'
      - run: pip install yamllint
        name: Install yamllint
      - run: yamllint -f parsable -c .yamllint-config.yml ${{matrix.files}}
        name: Run yamllint on ${{matrix.version}} descriptions
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install Node modules
        run: npm ci
      # TODO: update script to pass in {{files}} so that this can support 3.1
      - name: JSON Lint
        run: npm run lint
      - name: OpenAPI Lint
        uses: mattpage/redocly-cli-lint-action@v0.0.1
        with:
          # TODO: use matrix.files variable when workflow is ready to process 3.1 files
          entrypoints: 'descriptions/**/*.yaml'
          config: '.redocly.yml'
